# name: Output Data
# on: workflow_dispatch
# jobs:
#     output_job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Output github context
#               run: echo "${{toJson(github)}}"